### ISSUE TITLE
Gerenciamento de Ciclos de Entrega: Como um administrador, eu quero editar o peso de cada ciclo de entrega de uma turma.

### ISSUE THREAD

**Issue by MateusMSoares** [ClaraSantosmf/FATEC-API-1-SEMESTRE#105]
Regra de negócio:
**Os pesos só podem ser alterados se o ciclo correspondente ainda não foi fechado.** 

 **Frontend:
- A tela corresponde a edição de turma.
- Os pesos podem ser alterados em mais detalhes da turma.
- Sugestão de tela: mais_detalhes_turma.html

![Tela edição de nota e ciclos](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/c85fe858-e36c-4408-a808-959a75b08317)

**Comment by caiopalma** [comment]
Eu faço!
