### ISSUE TITLE
Gerenciamento de Ciclos de Entrega: Armazenando o valor de cada ciclo em uma turma, e a média dos alunos

### ISSUE THREAD

**Issue by MateusMSoares** [ClaraSantosmf/FATEC-API-1-SEMESTRE#106]
- Desenvolver lógica que possibilite que as turmas tenham peso de ciclo variavel.
Embora o numero de ciclos e dias de cada ciclo seja global, o peso deve ser definido a cada turma

- Necessário definir onde será salvo a média dos alunos
- - FEE total e parcial. Qual o cálculo do FEE?	FEE = ((Score do Ciclo de Entrega 1 (C1) * Peso de C1) + ... + (Score do Ciclo de Entrega N (CN) * Peso de CN)) / Soma dos Pesos de C

**Comment by sararobertnahra** [comment]
Quero esse!

**Comment by caiopalma** [comment]
## A estrutura proposta para o armazenamento de pesos dos ciclos:

```JSON
{
    "1": {
        "nome": "Turma Teste",
        "professor": "Professora teste",
        "data_de_inicio": "2023-10-11",
        "ciclos": {
            "1":{
                "peso": 1.0
            },
            "2":{
                "peso": 2.0
            },
            "3":{
                "peso": 2.0
            },
            "4":{
                "peso": 2.0
            }
        }
    }
}
```

## Criar função para adicionar dinamicamente os ciclos no ato da criação da turma, já atribuindo o peso padrão igual ao número do ciclo.

## A estrutura proposta para o armazenamento do fee:

```JSON
{
  "1": {
    "nome": "Clara Santos",
    "fee": 9.0
  },
  "2": {
    "nome": "Marcelo Tambalo",
    "fee": 10.0
  },
  "3": {
    "nome": "TA RA RA RA",
    "fee": 7.0
  }
}
```
