### ISSUE TITLE
Apresentação sprint 3: Preparar o esqueleto da apresentação.

### ISSUE THREAD

**Issue by sararobertnahra** [ClaraSantosmf/FATEC-API-1-SEMESTRE#114]
Apresentação da sprint 3:

Responsáveis pela apresentação: Sara e Ruth

Pensamos em fazer uma apresentação no power point ou um arquivo em markdown com os vídeos rodando da parte do front. 

Iniciamos a apresentação falando quem somos, nossa função no grupo e o nome do grupo que pertencemos (15s). Após isso, falamos sobre o que foi feito até agora (30 s) o que fizemos nos últimos dias (30 s) como anda os próximos planejamentos (30 s)

Depois mostramos o vídeo (1 min 30s) e mostramos a parte do código  também, que já vai estar no power point ou arquivo md. (1 min).

Anotem as sugestões pra encaixarmos na apresentação!

**Comment by RuthMira** [comment]
oi
