### ISSUE TITLE
Gerenciamento de Ciclos de Entrega: Como administrador eu quero visualizar o FEE dos alunos da turma

### ISSUE THREAD

**Issue by RuthMira** [ClaraSantosmf/FATEC-API-1-SEMESTRE#134]
Regra de negocio:
O FEE denominado parcial é aquele que leva em conta apenas as notas dos ciclos já inseridos pelo usuário. Já o FEE total é aquele que efetua o cálculo com base em todas as notas já inseridas, em todos os ciclos.

Media: FEE total e parcial. Qual o cálculo do FEE? FEE = ((Score do Ciclo de Entrega 1 (C1) * Peso de C1) + ... + (Score do Ciclo de Entrega N (CN) * Peso de CN)) / Soma dos Pesos de C

**Frontend:
- Sugestão de consulta: mais_detalhes_turmas.html
- Visualizar o FEE dos alunos da turma

** Backend:
- Módulo gerenciador_ciclos.py com funções para as notas de ciclos de entrega.
- Rota de API: ("/api/v1/notas/fee/obter/:id_turma/:id_aluno")

**Comment by sararobertnahra** [comment]
oi
