### ISSUE TITLE
[Débito Técnico] Colocar o nome do ciclo na coluna em que as notas daquele ciclo serão exibidas

### ISSUE THREAD

**Issue by danitamazato** [ClaraSantosmf/FATEC-API-1-SEMESTRE#145]
Na tela de inserir notas, o usuário precisa identificar qual o ciclo está sendo abastecido na coluna.

**Comment by RuthMira** [comment]
regra de negocio: As notas só poderão ser atribuídas no prazo de: final do ciclo + 1 dia até 5 dias após o final.

Frontend:

Na tela mais informacoes_turma .html: mostrar qual o ciclo de notas esta aberto para o lançamento, qual esta fechado.
(cadeado na coluna de cada ciclo ou cores do input de cada nota):

![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049504/7d52c6d8-89a3-434a-ae16-aad9d911a4a1)
