### ISSUE TITLE
[Débito Técnico] Não permitir que notas fiquem menores que 0 e maiores que 10

### ISSUE THREAD

**Issue by danitamazato** [ClaraSantosmf/FATEC-API-1-SEMESTRE#171]
<!DOCTYPE html>
<html>
<body>

<input type="number" id="myNumberInput" min="0" max="100">

<script>
const inputElement = document.getElementById("myNumberInput");

inputElement.addEventListener("input", function(event) {
    const value = event.target.value;
    if(value < 0) {
        event.target.value = 0; // Define o valor para 0 se for menor que 0
    }
    if(value > 100) {
        event.target.value = 100; // Define o valor para 100 se for maior que 100
    }
});
</script>

</body>
</html>

http://127.0.0.1:5500/front/informacoes_turma.html?id=1

**Comment by RuthMira** [comment]
OI
