### ISSUE TITLE
Gerenciamento de turma: Como um administrador, eu quero criar uma nova turma

### ISSUE THREAD

**Issue by MateusMSoares** [ClaraSantosmf/FATEC-API-1-SEMESTRE#19]
Preciso de uma forma de criação de turma com nome da turma, o professor e a associação de grupos pré-existentes ou nenhum grupo.  A turma não precisa ser criada com grupo de alunos, mas precisa poder recebê-los. A turma só será ativa com grupo de alunos vinculados.

**Frontend:**

- [ ] Template HTML para criação  de Turmas: 
- [ ] criar_turma.html que conterá os formulários para criar uma nova turma.
- [ ] A inclusão de grupos de alunos não precisa ser obrigatória.
- [ ] Nome da turma e professor são obrigatórios.
- [ ] Campo para procurar por um grupo pré-existente
- [ ] Campo para listar grupos 

**Backend:**

- [ ] Módulo gerenciador_turmas.py com funções para criar uma turma com/sem novo grupo de alunos.
- [ ] /api/turmas/criar: Manipula a criação de uma nova turma.
- [ ] /api/grupos /listar: Manipula a lista de grupos preexistente

**Comment by marilia-borgo** [comment]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/101718104/126682e2-622f-4823-9b34-3687e8597675)

**Comment by marilia-borgo** [comment]
No escopo de entrega dessa task, não é necessário entregar a listagem de grupos.

**Comment by MateusMSoares** [comment]
Criando modal para criação de turmas
