### ISSUE TITLE
Gerenciamento de turma:  Como um administrador, eu quero editar as informações de uma turma

### ISSUE THREAD

**Issue by MateusMSoares** [ClaraSantosmf/FATEC-API-1-SEMESTRE#20]
Como administrador, quero editar uma turma e seus respectivos grupos se houver. 

FrontEnd
editar_turma.html que conterá os formulários de edição de uma nova turma, com possibilidade de ser levada a edição de grupo e de criar novo grupo. 

Backend:

- Módulo gerenciador_turmas.py com funções para atualizar informações de turma e editar grupo de alunos.
- Rotas de API:

/api/turmas/atualizar/{id}: Manipula a atualização das informações de uma turma específica.
/api/grupos/atualizar/{id}: Manipula a atualização das informações de um grupo de alunos específico.

**Comment by marilia-borgo** [comment]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/101718104/f3385a67-b5fd-4be0-9443-8bd7014b0334)

**Comment by caiopalma** [comment]
Atividades previstas:

- [ ] Criar módulo com funções editar turma e editar grupo 
- [ ] Criar rota de api para editar turma.
- [ ] Criar rota de api para editar grupo.
- [ ] Implementar página do formulário de edição de turma.
    - [ ] Dado o Id da turma, preencher os campos do formulário.
    - [ ] Incluir redirecionamento para 'Novo Grupo'.
    - [ ] Incluir redirecionamento para 'Editar Grupo'.
- [ ] Criar componente para listagem de grupos

**Comment by sararobertnahra** [comment]
Aqui
