### ISSUE TITLE
Gerar relatório / Dashboard: Como administrador, quero gerar o relatório de uma turma com visualização em tela no site

### ISSUE THREAD

**Issue by danitamazato** [ClaraSantosmf/FATEC-API-1-SEMESTRE#208]
* tela - parte superior: mostrar, utilizando gráfico de barras, as médias de todas as turmas em um deteminado intervalo de tempo
* tela - parte inferior: selecionar a turma; em seguida, mostrar gráfico com nota de cada aluno e média geral da turma.

![image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/2ef5f058-e5df-42ff-ab44-866f73261e83)

**Comment by RuthMira** [comment]
Regra de Négocio:

Front-end:
Exportaçao_dados.html  - listar todas as informações seguindo o modelo de Excel (tabela de dados.

Back-end:
rota  das informações que estão na tabela modelo.

**Comment by sararobertnahra** [comment]
euuu
