### ISSUE TITLE
[Débito Técnico] Na tela de editar aluno, a data não é armazenada.

### ISSUE THREAD

**Issue by danitamazato** [ClaraSantosmf/FATEC-API-1-SEMESTRE#211]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/a2658a6c-c767-474d-ae77-944d84764381)

**Comment by danitamazato** [comment]
@sararobertnahra

**Comment by sararobertnahra** [comment]
@caiopalma
