### ISSUE TITLE
[MELHORIA] Possibilitar que o usuário renomeie o nome do ciclo (ao invés de C1, o usuário escolhe o nome que desejar)

### ISSUE THREAD

**Issue by danitamazato** [ClaraSantosmf/FATEC-API-1-SEMESTRE#221]
"Adendo em relação ao Ciclo de Entregas da forma como está implementado no projeto de vocês:
Considerem uma melhoria que possibilite inserir um nome personalizado para o Ciclo de Entrega ao invés do C1, C2, etc atuais."

- A edição dos ciclos e edição dos pesos podem ser feitos na mesma página
- A  quantidade de Ciclos de Entrega podemos manter no Global Settings mas tomando o cuidado de:

1. Dar a opção de redefinir um peso específico para cada Ciclo de Entrega por Turma definida; e
2. Dar a opção para que o usuário defina o rótulo (ou seja, o nome que ele quiser) do Ciclo de Entrega (podemos padronizar o nome com C1, C2 etc no momento da criação da turma, com possibilidade para editar no futuro caso o usuário queira)

**Comment by danitamazato** [comment]
@caiopalma ^^

**Comment by caiopalma** [comment]
eu
