### ISSUE TITLE
gerenciamento de alunos: Como um administrador, eu quero adicionar um novo aluno com informações pessoais e matrícula

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#23]
front: 
- Template HTML para Adicionar Alunos:	
 gerenciamento_alunos.html que conterá o formulário para adicionar um novo aluno

- Está no escopo dessa task fazer o botão de redirecionamento da página de listagem para a página de edição de alunos.

Backend:

-  Módulo gerenciador_alunos.py com funções para adicionar um aluno. 

- Rotas de API: /api/alunos/adicionar: Manipula a adição de um novo aluno.

**Comment by marilia-borgo** [comment]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/101718104/3ff9b535-48de-4a90-940a-d31bbb7849a9)

**Comment by caiopalma** [comment]
Eu vou fazer essa! 🤓
