### ISSUE TITLE
gerenciamento de alunos: Como um administrador, eu quero excluir alunos.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#25]
front: 

- Nessa não é necessário criar uma página .html, a confirmação de exclusão será feita em um alert.

- Está no escopo dessa task a funcionalidade do botão de exclusão do botão de exclusão do aluno.

Backend:

-  Módulo gerenciador_alunos.py com funções para excluir alunos.

- Rotas de API: /api/alunos/excluir/{id}: Manipula a atualização das informações de um aluno específico

**Comment by marilia-borgo** [comment]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/101718104/d40430b4-d153-4ecc-9db5-7223e9576ef1)

**Comment by willigfreitas** [comment]
ME COLOCAR COMO RESPONSÁVEL POR ESSA TASK, POR FAVOR.
