### ISSUE TITLE
gerenciamento de turmas:  Como um administrador, eu quero excluir uma turma.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#26]
Frontend:

- Ícone de exclusão do grupo

backend:

- Módulo gerenciador_turmas.py com funções para excluir turmas.

- Rotas de API:/api/turmas/excluir/{id}: Manipula a exclusão de uma turma específica.

**Comment by marilia-borgo** [comment]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/101718104/c6f7bb85-84c2-4a4d-902c-c8c1e86b0793)

**Comment by sararobertnahra** [comment]
Já temos essa parte pronta! Podemos ficar com essa tarefa?

**Comment by caiopalma** [comment]
PR aberta.
