### ISSUE TITLE
Gerenciamento de Grupos: Como administrador, quero ver todos os grupos formados e associados às turmas.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#29]
Frontend:
- Template HTML para visualização de grupos: 
gerenciamento_grupos.html que conterá todos os grupos já criados com ícone de edição e de exclusão em cada um deles.  
- Cada grupo deve apresentar seu nome e respectiva turma.

Backend:

- Módulo gerenciador_grupos.py com funções para listar os grupos associados às turmas. 

- Rotas de API:/api/grupos/listar: Manipula a listagem de grupos.

**Comment by MateusMSoares** [comment]
Teste

**Comment by sararobertnahra** [comment]
Eu!
