### ISSUE TITLE
Gerenciamento de Grupos: Como um administrador, eu quero criar grupos de alunos associado a uma turma.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#30]
frontend:

- Template HTML para criar um grupo: 

- criar_grupo.html que conterá os formulários de criação de um novo grupo

- Selecionar a qual turma ele pertencerá.

- Para adicionar um grupo é necessário inserir o nome do grupo e a turma.

backend:

-  Módulo gerenciador_grupo.py com funções para adicionar pré-existente, e associar esse grupo a uma turma. 
- Rotas de API: /api/tumas/listar: Fazer a leitura das turmas existente, /api/grupos/adicionar: Manipula a adição de um novo grupo a uma turma.

**Comment by danitamazato** [comment]
Olá!

**Comment by danitamazato** [comment]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/65ccabc1-c4e2-4506-abe9-98b954cde02c)
