### ISSUE TITLE
Gerenciamento de Grupos:  como um administrador, eu quero editar grupos, essas devem ser associado a uma turma.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#31]
frontend:

- Template HTML para Gerenciamento de um grupo: 

- editar_grupo.html conterá as informações do grupo selecionado

- Pode levar a visualização das notas do aluno.

Backend:

- Módulo gerenciador_grupo.py com funções para adicionar alunos pré-existente, excluir aluno do grupo e editar qual turma esse grupo está associado.
- Rotas de API: /api/grupos/editar/{id}: Manipula para editar grupos.

**Comment by RuthMira** [comment]
oi
