### ISSUE TITLE
Gerenciamento de Grupos: Como administrador, quero excluir os grupos.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#32]
Front end:

- Template HTML para visualização de grupos: 

- visualizacar_grupos.html que conterá todos os grupos já criados com ícone de edição e de exclusão em cada um deles.  

- O icone deve acionar a ação de excluir 

backend:
-  Módulo gerenciador_grupos.py com funções para excluir o aluno selecionado. 
- Rotas de API:
 /api/grupos/excluir/{id}: Manipula a listagem de grupos, excluindo o selecionado.

**Comment by MateusMSoares** [comment]
Minha tarefa

**Comment by marilia-borgo** [comment]
A gente não vai mais fazer grupo.
