### ISSUE TITLE
Gerenciamento de Ciclos de Entrega e Scores: Como um administrador, eu quero visualizar(listar) as notas de um aluno em uma turma.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#33]
Frontend:

- Em mais informações de uma turma deve listar os alunos e suas respectivas notas.
- Média: FEE total e parcial. Qual o cálculo do FEE?	FEE = ((Score do Ciclo de Entrega 1 (C1) * Peso de C1) + ... + (Score do Ciclo de Entrega N (CN) * Peso de CN)) / Soma dos Pesos de C

Backend:

- Módulo gerenciador_ciclos.py com funções para listar as turmas e as notas associadas aquele aluno.

- Rotas de API: /api/notas/listar/aluno/{id}: Manipula a lista de um novo ciclo de entrega

Print da tela:
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/74261014/c8594780-ef6d-4920-95b8-7223458bdd0b)

![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/74261014/e66a42b9-4c3f-41d4-8c8a-afb8a162885b)

**Comment by MateusMSoares** [comment]
Libera para eu editar

**Comment by danitamazato** [comment]
Olar!

**Comment by RuthMira** [comment]
Oi
