### ISSUE TITLE
Gerenciamento de Ciclos de Entrega: Como um administrador, eu quero editar as notas de entrega existente.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#35]
regra de negocio:
As notas só poderão ser editadas no prazo de: final do ciclo + 1 dia até 5 dias após o final.
- Media: FEE total e parcial. Qual o cálculo do FEE?	FEE = ((Score do Ciclo de Entrega 1 (C1) * Peso de C1) + ... + (Score do Ciclo de Entrega N (CN) * Peso de CN)) / Soma dos Pesos de C

**Frontend:

 - Notas serão editadas em mais detalhes de turmas.**

Backend:

- Módulo gerenciador_ciclos.py com funções para as notas de ciclos de entrega.

- Rotas de API: (/api/v1/notas/editar:id_nota)
            -Manipula a atualização da nota em uma determinada entrega específica.

![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/74261014/7843deae-1939-49e7-8678-ee893cd8ead0)

**Comment by MateusMSoares** [comment]
Libera para eu editar

**Comment by sararobertnahra** [comment]
Oi
