### ISSUE TITLE
Carregamento de Dados massivo: Como um administrador, eu quero carregar informações de alunos a partir de arquivos.

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#39]
Frontend: 

- Tela de index.html terá um botão para update para o carregamento do CSV

Backend:

- Módulo carregamento_dados.py com funções para carregar informações de alunos e scores a partir de um arquivo CSV.

- Função para autenticar o formato do CSV, ou seja, ver se está dentro dos padrões

- Função para realizar o cadastramento de cada um dos alunos. 

- Rotas de API:/api/carregamento: Manipula o carregamento de dados a partir de arquivos.

Detalhes necessários:
 
- [ ] * definir planilha padrão
- [ ] * telas 1: carregar arquivo
- [ ] * tela 1: selecionar a turma
- [ ] * tela 1: iniciar importação
- [ ] * tela: redirecionar para a tela da turma que acabou de ser criada

![epic7-hist1](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/8a97754b-a048-4de8-aaaf-b3c7fd750013)

**Comment by MateusMSoares** [comment]
eu

**Comment by danitamazato** [comment]
![Captura de tela 2023-11-06 222940](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/7157630f-9d0d-427c-b6df-8fc0324d2972)


![Captura de tela 2023-11-04 233757](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/e0a60067-558e-46a4-8301-5f7cf0dd642c)


![Captura de tela 2023-11-04 233820](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/489fd606-8332-419f-8846-133e09396eda)



![Captura de tela 2023-11-08 235516](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/8ff67a14-93c4-4ce2-abfa-8075d808b7d6)



![Captura de tela 2023-11-04 233857](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/a3825f55-d221-4701-b994-fbcf5f272132)

**Comment by RuthMira** [comment]
eu
