### ISSUE TITLE
Elaboração do Index.

### ISSUE THREAD

**Issue by ClaraSantosmf** [ClaraSantosmf/FATEC-API-1-SEMESTRE#46]
Elaboração do frontend com redirecionamento. 

![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/92645535/3f60e258-625e-4823-83e9-c2da986cd2eb)

**Comment by danitamazato** [comment]
> Elaboração do frontend com redirecionamento.
> 
> ![Imagem](https://user-images.githubusercontent.com/92645535/270498415-3f60e258-625e-4823-83e9-c2da986cd2eb.png)

**Principais:**

- [ ] 

**Adicionais:**

- [ ] Cabeçalho e rodapé
- [ ] Background adicional (vetores) por repeat
- [ ] Estilização dos botões

**Etapa Final:**
Dependemos dos links para finalizar redirecionamento

**Comment by RuthMira** [comment]
oi
