### ISSUE TITLE
[Débito técnico] Salvar um datetime no json

### ISSUE THREAD

**Issue by marilia-borgo** [ClaraSantosmf/FATEC-API-1-SEMESTRE#83]
![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/101718104/c30398df-babe-43b3-afbf-d753bcc581fa)

O objetivo é que não aconteça essa diferença de formatação ⬆ 

Na hora de salvar as turmas a gente salva uma string que vem do front, mas isso é ruim pq as vezes ela pode vir com` \ `as vezes com `-` e isso impacta na hora de fazer qualquer cálculo com datas.

Entregável:

- no arquivo gerenciamento_turmas, antes de salvar no json tranformar em um objeto datetime e depois salvar essa string no json.

**Comment by willigfreitas** [comment]
Atribua para mim, por favor.

**Comment by marilia-borgo** [comment]
@willigfreitas vou te atribuir, e aqui tem uma docuemntaçãozinha pra vc entender melhor o que tem que fazer https://www.alura.com.br/artigos/lidando-com-datas-e-horarios-no-python

**Comment by willigfreitas** [comment]
Tinha testado o código pelo visto fiz o que você pediu.
Veja por favor.
